freight/urls.py
from django.urls import path

from . import views

app_name = "freight"

urlpatterns = [
    path("", views.index, name="index"),
    path(
        "setup_contract_handler",
        views.setup_contract_handler,
        name="setup_contract_handler",
    ),
    path("add_location", views.add_location, name="add_location"),
    path("add_location_2", views.add_location_2, name="add_location_2"),
    path("calculator", views.calculator, name="calculator"),
    path("calculator/<int:pricing_pk>", views.calculator, name="calculator"),
    path("contract_list_all", views.contract_list_all, name="contract_list_all"),
    path("contract_list_user", views.contract_list_user, name="contract_list_user"),
    path(
        "contract_list_data/<str:category>",
        views.contract_list_data,
        name="contract_list_data",
    ),
    path("statistics", views.statistics, name="statistics"),
    path(
        "statistics_routes_data",
        views.statistics_routes_data,
        name="statistics_routes_data",
    ),
    path(
        "statistics_pilots_data",
        views.statistics_pilots_data,
        name="statistics_pilots_data",
    ),
    path(
        "statistics_pilot_corporations_data",
        views.statistics_pilot_corporations_data,
        name="statistics_pilot_corporations_data",
    ),
    path(
        "statistics_customer_data",
        views.statistics_customer_data,
        name="statistics_customer_data",
    ),
]

freight/forms.py
import math

from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator

from .models import Pricing


class CalculatorForm(forms.Form):
    pricing = forms.ModelChoiceField(
        queryset=Pricing.objects.select_related("start_location", "end_location")
        .filter(is_active=True)
        .order_by("start_location__name", "end_location__name"),
        label="Route",
        help_text="Pick a route for your courier contract",
        empty_label=None,
    )
    volume = forms.IntegerField(
        help_text="Est. volume of your cargo in m3",
        required=False,
        validators=[MinValueValidator(0)],
    )
    collateral = forms.IntegerField(
        help_text=(
            "Collateral in ISK, must be roughly equal to the est. "
            "value of your cargo"
        ),
        required=False,
        validators=[MinValueValidator(0)],
    )

    def clean(self):
        pricing = self.cleaned_data.get("pricing")
        if pricing:
            issue_prefix = "⚠ Issues:"

            if pricing.requires_volume() and self.cleaned_data["volume"] is None:
                raise ValidationError("{} volume is required".format(issue_prefix))

            if (
                pricing.requires_collateral()
                and self.cleaned_data["collateral"] is None
            ):
                raise ValidationError("{} collateral is required".format(issue_prefix))

            volume = self.cleaned_data["volume"]
            collateral = self.cleaned_data["collateral"]
            issues = pricing.get_contract_price_check_issues(volume, collateral)

            if issues:
                raise ValidationError("{} {}".format(issue_prefix, ", ".join(issues)))

    def get_calculated_data(self, pricing: object) -> tuple:
        if self.is_valid():
            if self.cleaned_data["volume"]:
                volume = int(self.cleaned_data["volume"])
            else:
                volume = 0
            if self.cleaned_data["collateral"]:
                collateral = int(self.cleaned_data["collateral"])
            else:
                collateral = 0
            price = (
                math.ceil(pricing.get_calculated_price(volume, collateral) / 1000000)
                * 1000000
            )

        else:
            volume = None
            collateral = None
            price = None

        return volume, collateral, price


class AddLocationForm(forms.Form):
    location_id = forms.IntegerField(
        label="Location ID",
        help_text="Eve Online ID for a station or an Upwell structure",
    )

freight/templates/freight/add_location.html
{% extends 'freight/base.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}

{% block details %}
    <form class="form" action="{% url 'freight:add_location_2' %}" method="POST">
        {% csrf_token %}
        {{ form|bootstrap }}
        <button class="btn btn-success btn-block" type="submit">Add / Update Location</button>
        <p class="text-muted">Accessing structures with token from <strong>{{ token_char_name }}</strong></p>
    </form>
{% endblock %}

freight/templates/freight/base.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}
{% block page_title %}{{ app_title }}{% endblock %}

{% block content %}
    <br />
    {% include 'freight/partials/menu.html' %}
    <h2>{{ page_title }}</h2>
    {% block details %}{% endblock %}
{% endblock %}

freight/templates/freight/calculator.html
{% extends 'freight/base.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}
{% load static %}
{% load freight_filters %}

{% block details %}
    <form id="form_calculator" class="form" action="{% url 'freight:calculator' %}" method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Calculator</h3>
                    </div>
                    <div class="panel-body">
                        {% if has_pricing %}
                            {{ form|bootstrap }}
                            <br>
                            <p><strong>Reward</strong></p>
                            <h2 id="text_price">
                                <span id="text_price_2">{{ price|formatnumber:"0"|default_if_none:"-" }} ISK</span>
                                <span class="copy_to_clipboard" data-text="{{ price }}">
                                    &nbsp;&nbsp;<i class="far fa-copy"></i></span>
                                </span>
                            </h2>
                                <button class="btn btn-success btn-lg" type="submit">Click To Calculate Reward!</button>
                        {% else %}
                            <p class="text-warning">Please define a pricing/route!</p>
                        {% endif %}
                    </div>
                </div>
            </div>

            <div class="col-md-6">

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Pricing details</h3>
                    </div>

                    <div class="panel-body" style="min-height: 100px;">

                        {% if pricing %}
                            <dl class="dl-horizontal">
                                {% if pricing.is_bidirectional %}
                                    <dt>From / To:</dt>
                                {% else %}
                                    <dt>From:</dt>
                                {% endif %}

                                <dd>{{ pricing.start_location }}</dd>

                                {% if pricing.is_bidirectional %}
                                    <dt>From / To:</dt>
                                {% else %}
                                    <dt>To:</dt>
                                {% endif %}
                                <dd>{{ pricing.end_location }}</dd>

                                <dt>Both directions:</dt>
                                <dd>{{ pricing.is_bidirectional|yesno }}</dd>
                                <br>

                                {% if pricing.price_min != None %}
                                    <dt>Minimum price:</dt>
                                    <dd>{{ pricing.price_min|formatnumber:"0" }} ISK</dd>
                                {% endif %}

                                {% if pricing.price_base != None %}
                                    {% if pricing.is_fix_price %}
                                        <dt>Fix price:</dt>
                                    {% else %}
                                        <dt>Base price:</dt>
                                    {% endif %}
                                    <dd>{{ pricing.price_base|formatnumber:"0" }} ISK</dd>
                                {% endif %}

                                {% if pricing_price_per_volume_eff != None %}
                                    <dt>Price add-on per m3:</dt>
                                    <dd>{{ pricing_price_per_volume_eff|formatnumber:"0" }} ISK</dd>
                                {% endif %}

                                {% if pricing.price_per_collateral_percent != None %}
                                    <dt>Price add-on collateral:</dt>
                                    <dd>{{ pricing.price_per_collateral_percent }} %</dd>
                                {% endif %}

                                <br>
                                {% if pricing.volume_min != None %}
                                    <dt>Min Volume:</dt>
                                    <dd>{{ pricing.volume_min|formatnumber:"0"|default_if_none:"-" }} m3</dd>
                                {% endif %}

                                {% if pricing.volume_max != None %}
                                    <dt>Max Volume:</dt>
                                    <dd>{{ pricing.volume_max|formatnumber:"0"|default_if_none:"-" }} m3</dd>
                                {% endif %}

                                {% if pricing.collateral_min != None %}
                                    <dt>Min. Collateral:</dt>
                                    <dd>{{ pricing.collateral_min|formatnumber:"0" }} ISK</dd>
                                {% endif %}

                                {% if pricing.collateral_max != None %}
                                    <dt>Max. Collateral:</dt>
                                    <dd>{{ pricing.collateral_max|formatnumber:"0" }} ISK</dd>
                                {% endif %}

                                <br>

                                {% if pricing.details %}
                                    <dt>Additional Instructions:</dt>
                                    <dd>{{ pricing.details|linebreaks }}</dd>
                                {% endif %}

                            </dl>

                        {% else %}
                            <p class="text-warning">Please define a pricing/route!</p>
                        {% endif %}

                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Your contract</h3>
                    </div>
                    <div class="panel-body" style="min-height: 100px;">
                        {% if price != None %}
                            <dl class="dl-horizontal">
                                <dt>Contract Type:</dt>
                                <dd>Courier</dd>

                                <dt>Availability:</dt>
                                <dd>{{ availability }}</dd>

                                <dt>Location:</dt>
                                <dd>
                                    {{ pricing.start_location }}
                                    <span class="copy_to_clipboard" data-text="{{ pricing.start_location }}">
                                        &nbsp;&nbsp;<i class="far fa-copy"></i></span>
                                    </span>
                                </dd>

                                <hr>

                                <dt>Ship To:</dt>
                                <dd>
                                    {{ pricing.end_location }}
                                    <span class="copy_to_clipboard" data-text="{{ pricing.end_location }}">
                                        &nbsp;&nbsp;<i class="far fa-copy"></i></span>
                                    </span>
                                </dd>

                                <dt>Reward:</dt>
                                <dd>
                                    {{ price|formatnumber:"0"|default_if_none:"???" }} ISK
                                    <span class="copy_to_clipboard" data-text="{{ price }}">
                                        &nbsp;&nbsp;<i class="far fa-copy"></i></span>
                                    </span>
                                </dd>

                                <dt>Collateral:</dt>
                                <dd>
                                    {{ collateral|formatnumber:"0"|default_if_none:"???" }} ISK
                                    <span class="copy_to_clipboard" data-text="{{ collateral }}">
                                        &nbsp;&nbsp;<i class="far fa-copy"></i></span>
                                    </span>
                                </dd>

                                {% if pricing.days_to_expire %}
                                    <dt>Expiration:</dt>
                                    <dd>{{ pricing.days_to_expire }} days ({{ expires_on|date:'Y-m-d' }})</dd>
                                {% endif %}

                                {% if pricing.days_to_complete %}
                                    <dt>Days to complete:</dt>
                                    <dd>
                                        {{ pricing.days_to_complete|default_if_none:"-" }}
                                        <span class="copy_to_clipboard" data-text="{{ pricing.days_to_complete }}">
                                            &nbsp;&nbsp;<i class="far fa-copy"></i></span>
                                        </span>
                                    </dd>
                                {% endif %}

                                {% if pricing.requires_volume %}
                                    <dt>Volume:</dt>
                                    <dd>{{ volume|formatnumber:"0"|default_if_none:"???" }} m3</dd>
                                {% endif %}

                                <hr>
                                Note that this route is bidirectional, so Location and Destination can be switched.
                            </dl>

                        {% else %}
                            <p class="text-muted">No price calculated yet</p>
                        {% endif %}
                    </div>
                </div>

            </div>
        </div>

    </form>
<br>

{% endblock %}

{% block extra_javascript %}
    <script type="application/javascript">
        function copyToClipboard(text) {
            if (window.clipboardData && window.clipboardData.setData) {
                // IE specific code path to prevent textarea being shown while dialog is visible.
                return clipboardData.setData("Text", text);
            } else if (document.queryCommandSupported && document.queryCommandSupported("copy")) {
                const textarea = document.createElement("textarea");
                textarea.textContent = text;
                textarea.style.position = "fixed";  // Prevent scrolling to bottom of page in MS Edge.
                document.body.appendChild(textarea);
                textarea.select();
                try {
                    return document.execCommand("copy");  // Security exception may be thrown by some browsers.
                } catch (ex) {
                    console.warn("Copy to clipboard failed.", ex);
                    return false;
                } finally {
                    document.body.removeChild(textarea);
                }
            }
        }

        $(document).ready(function(){
            /* redirecting to updated calculator view with chosen pricing */
            $("#id_pricing").change(function(){
                let value = $("#id_pricing").val();
                if (value == null) {
                    value = 0;
                }
                window.location.replace(
                    "{% url 'freight:calculator' 0 %}".replace("0", value)
                );
            });

            $('.copy_to_clipboard').on('click', function (event) {
                const text = event.currentTarget.getAttribute("data-text")
                copyToClipboard(text)
            });
        });
    </script>
{% endblock %}

{% block extra_css %}
    <link href="{% static 'freight/css/kalkoken.css' %}" type="text/css" rel="stylesheet">
    <link href="{% static 'freight/css/calculator.css' %}" type="text/css" rel="stylesheet">
{% endblock %}

{% block extra_script %}
{% endblock %}

freight/templates/freight/contracts_all.html
{% extends 'freight/base.html' %}
{% load i18n %}
{% load humanize %}
{% load static %}

{% block details %}

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#active_contracts" aria-controls="active_contracts" role="tab" data-toggle="tab">Active</a></li>
        <li role="presentation"><a href="#all_contracts" aria-controls="all_contracts" role="tab" data-toggle="tab">All</a></li>
    </ul>

    <div class="panel panel-default panel-tab">
        <div class="panel-body">
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="active_contracts">
                    {% include "freight/partials/contract_table.html" with tab_name="tab_active_contracts" %}
                </div>
                <div role="tabpanel" class="tab-pane" id="all_contracts">
                    {% include "freight/partials/contract_table.html" with tab_name="tab_all_contracts" %}
                </div>
            </div>
        </div>
    </div>

    {% include "freight/partials/contracts_legend.html" %}


{% endblock %}

{% block extra_javascript %}

    {% include "freight/partials/contracts_js_includes.html" %}
    {% include "freight/partials/global_js.html" %}

    <script type="application/javascript">
        $(document).ready(function(){
            createContractsDataTable(
                "tab_active_contracts", "{% url 'freight:contract_list_data' 'active' %}"
            )
            createContractsDataTable(
                "tab_all_contracts", "{% url 'freight:contract_list_data' 'all' %}"
            )
        });
    </script>
{% endblock %}

{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}

    <link href="{% static 'freight/css/kalkoken.css' %}" type="text/css" rel="stylesheet">
    <link href="{% static 'freight/css/contracts.css' %}" type="text/css" rel="stylesheet">
{% endblock %}

{% block extra_script %}
{% endblock %}

freight/templates/freight/statistics.html
{% extends 'freight/base.html' %} {% load i18n %} {% load humanize %} {% load static %}
{% load freight_filters %} {% block details %}

<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
        <a href="#routes" aria-controls="routes" role="tab" data-toggle="tab">Routes</a>
    </li>
    <li role="presentation">
        <a href="#pilots" aria-controls="pilots" role="tab" data-toggle="tab">Pilots</a>
    </li>
    <li role="presentation">
        <a
            href="#pilot_corporations"
            aria-controls="pilot_corporations"
            role="tab"
            data-toggle="tab"
            >Pilot Corporations</a
        >
    </li>
    <li role="presentation">
        <a href="#customers" aria-controls="customers" role="tab" data-toggle="tab"
            >Customers</a
        >
    </li>
</ul>

<!-- Tabs -->
<div class="panel panel-default">
    <div class="panel-body">
        <div class="tab-content">
            <!-- Route -->
            <div role="tabpanel" class="tab-pane active" id="routes">
                <div class="table-responsive">
                    <table class="table table-striped table-width-fix" id="tab_routes">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Contracts</th>
                                <th>Rewards&nbsp;(ISK)</th>
                                <th>Collaterals&nbsp;(ISK)</th>
                                <th>Volume&nbsp;(m3)</th>
                                <th>Pilots</th>
                                <th>Customers</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                        <tfoot>
                            <tr class="success">
                                <th>TOTALS</th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>

            <!-- Pilots -->
            <div role="tabpanel" class="tab-pane" id="pilots">
                <div class="table-responsive">
                    <table class="table table-striped table-width-fix" id="tab_pilots">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Corporation</th>
                                <th>Contracts</th>
                                <th>Rewards&nbsp;(ISK)</th>
                                <th>Collaterals&nbsp;(ISK)</th>
                                <th>Volume&nbsp;(m3)</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                        <tfoot>
                            <tr class="success">
                                <th>TOTALS</th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>

            <!-- Pilot Corporations -->
            <div role="tabpanel" class="tab-pane" id="pilot_corporations">
                <div class="table-responsive">
                    <table
                        class="table table-striped table-width-fix"
                        id="tab_pilot_corporations"
                    >
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Alliance</th>
                                <th>Contracts</th>
                                <th>Rewards&nbsp;(ISK)</th>
                                <th>Collaterals&nbsp;(ISK)</th>
                                <th>Volume&nbsp;(m3)</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                        <tfoot>
                            <tr class="success">
                                <th>TOTALS</th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>

            <!-- Pilot Corporations -->
            <div role="tabpanel" class="tab-pane" id="customers">
                <div class="table-responsive">
                    <table
                        class="table table-striped table-width-fix"
                        id="tab_customers"
                    >
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Corporation</th>
                                <th>Contracts</th>
                                <th>Rewards&nbsp;(ISK)</th>
                                <th>Collaterals&nbsp;(ISK)</th>
                                <th>Volume&nbsp;(m3)</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                        <tfoot>
                            <tr class="success">
                                <th>TOTALS</th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<p class="text-muted">
    Statistics calculated for all contracts finished withn the last {{ max_days }} days
</p>

{% endblock %} {% block extra_javascript %} {% include 'bundles/datatables-js.html' %}
{% include "freight/partials/global_js.html" %}

<script type="application/javascript">
    // Remove the formatting to get integer data for summation
    function intVal(i)
    {
        return typeof i === 'string'
            ? i.replace(/[\$,]/g, '')*1
            : typeof i === 'number'
                ? i
                : 0;
    };

    $(document).ready(function(){
        $('#tab_routes').DataTable({
            ajax: {
                url: '{% url 'freight:statistics_routes_data' %}',
                dataSrc: 'data',
                cache: false
            },
            columns: [
                { data: 'name' },
                {
                    data: 'contracts',
                    render: $.fn.dataTable.render.number( ',', '.', 0 )
                },
                {
                    data: 'rewards',
                    render: $.fn.dataTable.render.formatisk()
                },
                {
                    data: 'collaterals',
                    render: $.fn.dataTable.render.formatisk()
                },
                {
                    data: 'volume',
                    render: $.fn.dataTable.render.number( ',', '.', 0 )
                },
                {
                    data: 'pilots',
                    render: $.fn.dataTable.render.number( ',', '.', 0 )
                },
                {
                    data: 'customers',
                    render: $.fn.dataTable.render.number( ',', '.', 0 )
                },
            ],
            order: [ [ 1, "desc" ], [ 2, "desc" ] ],
            footerCallback: function ( row, data, start, end, display ) {
                const api = this.api();
                dataTableFooterSumColumn(api, 1);
                dataTableFooterSumColumn(api, 2, "isk");
                dataTableFooterSumColumn(api, 3, "isk");
                dataTableFooterSumColumn(api, 4);
                dataTableFooterSumColumn(api, 5);
                dataTableFooterSumColumn(api, 6);
            }
        });

        $('#tab_pilots').DataTable({
            ajax: {
                url: '{% url 'freight:statistics_pilots_data' %}',
                dataSrc: 'data',
                cache: false
            },

            columns: [
                { data: 'name' },
                { data: 'corporation' },
                {
                    data: 'contracts',
                    render: $.fn.dataTable.render.number( ',', '.', 0 )
                },
                {
                    data: 'rewards',
                    render: $.fn.dataTable.render.formatisk()
                },
                {
                    data: 'collaterals',
                    render: $.fn.dataTable.render.formatisk()
                },
                {
                    data: 'volume',
                    render: $.fn.dataTable.render.number( ',', '.', 0 )
                },
            ],
            order: [ [ 2, "desc" ], [ 3, "desc" ] ],
            footerCallback: function ( row, data, start, end, display ) {
                const api = this.api();
                dataTableFooterSumColumn(api, 2);
                dataTableFooterSumColumn(api, 3, "isk");
                dataTableFooterSumColumn(api, 4, "isk");
                dataTableFooterSumColumn(api, 5);
            }
        });

        $('#tab_pilot_corporations').DataTable({
            ajax: {
                url: '{% url 'freight:statistics_pilot_corporations_data' %}',
                dataSrc: 'data',
                cache: false
            },

            columns: [
                { data: 'name' },
                { data: 'alliance' },
                {
                    data: 'contracts',
                    render: $.fn.dataTable.render.number( ',', '.', 0 )
                },
                {
                    data: 'rewards',
                    render: $.fn.dataTable.render.formatisk()
                },
                {
                    data: 'collaterals',
                    render: $.fn.dataTable.render.formatisk()
                },
                {
                    data: 'volume',
                    render: $.fn.dataTable.render.number( ',', '.', 0 )
                },
            ],
            order: [ [ 2, "desc" ], [ 3, "desc" ] ],
            footerCallback: function ( row, data, start, end, display ){
                const api = this.api();
                dataTableFooterSumColumn(api, 2);
                dataTableFooterSumColumn(api, 3, "isk");
                dataTableFooterSumColumn(api, 4, "isk");
                dataTableFooterSumColumn(api, 5);
            }
        });

        $('#tab_customers').DataTable({
            ajax: {
                url: '{% url 'freight:statistics_customer_data' %}',
                dataSrc: 'data',
                cache: false
            },

            columns: [
                { data: 'name' },
                { data: 'corporation' },
                {
                    data: 'contracts',
                    render: $.fn.dataTable.render.number( ',', '.', 0 )
                },
                {
                    data: 'rewards',
                    render: $.fn.dataTable.render.formatisk()
                },
                {
                    data: 'collaterals',
                    render: $.fn.dataTable.render.formatisk()
                },
                {
                    data: 'volume',
                    render: $.fn.dataTable.render.number( ',', '.', 0 )
                },
            ],
            order: [ [ 2, "desc" ], [ 3, "desc" ] ],
            footerCallback: function ( row, data, start, end, display ) {
                const api = this.api();
                dataTableFooterSumColumn(api, 2);
                dataTableFooterSumColumn(api, 3, "isk");
                dataTableFooterSumColumn(api, 4, "isk");
                dataTableFooterSumColumn(api, 5);
            }
        });
    });
</script>
{% endblock %} {% block extra_css %} {% include 'bundles/datatables-css.html' %}

<link href="{% static 'freight/css/kalkoken.css' %}" type="text/css" rel="stylesheet" />
<link
    href="{% static 'freight/css/statistics.css' %}"
    type="text/css"
    rel="stylesheet"
/>
{% endblock %} {% block extra_script %} {% endblock %}