freight/urls.py
from django.urls import path

from . import views

app_name = "freight"

urlpatterns = [
    path("", views.index, name="index"),
    path(
        "setup_contract_handler",
        views.setup_contract_handler,
        name="setup_contract_handler",
    ),
    path("add_location", views.add_location, name="add_location"),
    path("add_location_2", views.add_location_2, name="add_location_2"),
    path("calculator", views.calculator, name="calculator"),
    path("calculator/<int:pricing_pk>", views.calculator, name="calculator"),
    path("contract_list_all", views.contract_list_all, name="contract_list_all"),
    path("contract_list_user", views.contract_list_user, name="contract_list_user"),
    path(
        "contract_list_data/<str:category>",
        views.contract_list_data,
        name="contract_list_data",
    ),
    path("statistics", views.statistics, name="statistics"),
    path(
        "statistics_routes_data",
        views.statistics_routes_data,
        name="statistics_routes_data",
    ),
    path(
        "statistics_pilots_data",
        views.statistics_pilots_data,
        name="statistics_pilots_data",
    ),
    path(
        "statistics_pilot_corporations_data",
        views.statistics_pilot_corporations_data,
        name="statistics_pilot_corporations_data",
    ),
    path(
        "statistics_customer_data",
        views.statistics_customer_data,
        name="statistics_customer_data",
    ),
]

freight/templates/freight/partials/contract_table.html
 <div class="table-responsive">
    <table class="table table-striped table-width-fix tab-contract" id="{{ tab_name }}">
        <thead>
            <tr>
                <th>Status</th>
                <th>Start</th>
                <th>Destination</th>
                <th>Reward<br>&nbsp;ISK</th>
                <th>Collateral<br>&nbsp;ISK</th>
                <th>Volume<br>&nbsp;m3</th>
                <th>Contract<br>Check</th>
                <th>Issued<br>On</th>
                <th>Expires<br>On</th>
                <th>Issued<br>By</th>
                <th>Accepted<br>On</th>
                <th>Accepted<br>By</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>

freight/templates/freight/partials/contracts_js_includes.html
{% load static %}

{% include 'bundles/moment-js.html' with locale=True %}
{% include 'bundles/datatables-js.html' %}
{% include 'bundles/filterdropdown-js.html' %}

<script type="application/javascript" src="{% static 'freight/vendor/datatables/datetime.js' %}"></script>
<script type="application/javascript" src="{% static 'freight/js/contracts.js' %}"></script>

freight/templates/freight/partials/contracts_legend.html
<p class="text-muted">
    Contract check:&nbsp;&nbsp;
    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> = OK &nbsp;&nbsp;
    <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span> = Errors &nbsp;&nbsp;
    If they are errors you find them in the tooltip of icon &nbsp;&nbsp;
    <strong>-</strong> = No contract check performed
</p>
<p class="text-muted">
    Notes:&nbsp;&nbsp;
    <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> &nbsp;&nbsp;
    If icon is shown you can hover with the mouse over it to see the notes.
</p>
<p class="text-muted">
    Color code: <span class="text-info">In Progress</span> | <span class="text-warning">failed</span> | <span class="text-success">completed</span>
</p>

freight/templates/freight/partials/global_js.html
<!-- Global Javascript. Implemented as template, so we can use tags, filters and context. -->

<script type="text/javascript">
    /* Global constants */
    const DEFAULT_LENGTH_MENU = [[10, 25, 50, 100 -1], [10, 25, 50, 100, "All"]]
    const DEFAULT_PAGE_LENGTH = 50
    const B_DIVIDER = 9

    // Format ISK values for output
    // magnitude: show value with given magnitude, else magnitude will be calculated
    function formatisk(data, magnitude=null) {
        if ( data != null ) {
            const power_map = {'t': 12, 'b': 9, 'm': 6, 'k': 3, '': 0}
            if (!power_map.hasOwnProperty(magnitude)) {
                if (data >= 10 ** 12) magnitude = 't';
                else if (data >= 10 ** 9) magnitude = 'b';
                else if (data >= 10 ** 6) magnitude = 'm';
                else if (data >= 10 ** 3) magnitude = 'k';
                else magnitude = '';
            }
            return (data / (10 ** power_map[magnitude])).toLocaleString(
                'en-US', {minimumFractionDigits: 1, maximumFractionDigits: 1}
            ) + magnitude;
        }
        else return "";
    }

    // sum numbers in column and write result in footer row
    // Args:
    // - api: current api object
    // - columnIdx: Index number of columns to sum, starts with 0
    // - format: format of output. either 'number' or 'isk'
    function dataTableFooterSumColumn(api, columnIdx, format='number') {
        // Remove the formatting to get integer data for summation
        const intVal = function (i) {
            return typeof i === 'string' ?
                i.replace(/[\$,]/g, '') * 1 :
                typeof i === 'number' ?
                    i : 0;
        };

        const columnTotal = api
            .column(columnIdx)
            .data()
            .reduce(function (a, b) {
                    return intVal(a) + intVal(b);
                },
                0
            );
        let result;
        if (format == 'isk'){
            result = formatisk(columnTotal)
        } else {
            result = columnTotal.toLocaleString('en-US', {maximumFractionDigits: 0})
        }
        $(api.column(columnIdx).footer()).html(result);
    }

    // DataTables renderer for ISK values
    $.fn.dataTable.render.formatisk = function(magnitude=null) {
        return function ( data, type, row ) {
            if ( type === 'display' ) {
                return formatisk(data, magnitude);
            }
            // Search, order and type can use the original data
            return data;
        };
    };
</script>

freight/templates/freight/partials/menu.html
{% load static %}
{% load i18n %}
{% load navactive %}

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">{% trans "Toggle navigation" %}</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'freight:index' %}">{{ app_title }}</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                {% if perms.freight.use_calculator %}
                    <li class="{% navactive request 'freight:calculator' %}">
                        <a href="{% url 'freight:calculator' %}">Reward Calculator</a>
                    </li>

                    <li class="{% navactive request 'freight:contract_list_user' %}">
                        <a href="{% url 'freight:contract_list_user' %}">
                            My Contracts&nbsp;
                            {% if pending_user_count > 0 %}
                                <span class="badge badge-nav">{{ pending_user_count }}</span>
                            {% endif %}
                        </a>
                    </li>
                {% endif %}

                {% if perms.freight.view_contracts %}
                    <li class="{% navactive request 'freight:contract_list_all' %}">
                        <a href="{% url 'freight:contract_list_all' %}">
                            All Contracts&nbsp;
                            {% if pending_all_count > 0 %}
                                <span class="badge badge-nav">{{ pending_all_count }}</span>
                            {% endif %}
                        </a>
                    </li>
                {% endif %}

                {% if perms.freight.view_statistics %}
                    <li class="{% navactive request 'freight:statistics' %}">
                        <a href="{% url 'freight:statistics' %}">
                            Statistics
                        </a>
                    </li>
                {% endif %}
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if perms.freight.add_location %}
                    <a class="btn btn-default navbar-btn" href="{% url 'freight:add_location' %}">
                        Add Location
                    </a>
                {% endif %}

                {% if perms.freight.setup_contract_handler %}
                    <a class="btn btn-default navbar-btn" href="{% url 'freight:setup_contract_handler' %}">
                        {{ setup_contract_handler_label }}
                    </a>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>